-- GROUP BY와 ROLL UP, CUBE, GROUPING SETS

-- ROLL UP
-- ROLL UP은 순서가 중요하다!
-- 1) MANAGER_ID와 JOB_TITLE의 조합별 집계(MANAGE_ID가 ~일 때 JOB_TITLE이 ...인 행 개수)
-- 2) MANAGER_ID 로만 집계 (MANAGE_ID가 ~인 행 개수)
-- 3) 전체 집계 
SELECT MANAGER_ID, JOB_TITLE, COUNT(*) AS CNT
FROM EMPLOYEES
GROUP BY ROLLUP(MANAGER_ID, JOB_TITLE) 
ORDER BY MANAGER_ID, JOB_TITLE;


-- CUBE
-- ROLL UP과의 차이점? JOB_TITLE만 개별적으로 집계한다는 것
-- 1) MANAGER_ID 로만 집계
-- 2) JOB_TITLE 로만 집계
-- 3) MANAGER_ID와 JOB_TITLE의 조합별 집계
-- 4) 전체 집계
SELECT MANAGER_ID, JOB_TITLE, COUNT(*) AS CNT
FROM EMPLOYEES
GROUP BY CUBE(MANAGER_ID, JOB_TITLE) 
ORDER BY MANAGER_ID, JOB_TITLE;


-- GROUPING SETS
-- 내가 하고 싶은 컬럼만 선택해서 그룹핑할 수 있다
-- 자동으로 전체 집계는 안 나온다
-- 1) MANAGE_ID 로만 집계
-- 2) JOB_TITLE 로만 집계
SELECT MANAGER_ID, JOB_TITLE, COUNT(*) AS CNT
FROM EMPLOYEES
GROUP BY GROUPING SETS(MANAGER_ID, JOB_TITLE)
ORDER BY MANAGER_ID, JOB_TITLE;

-- GROUPING SETS((MANAGER_ID, JOB_TITLE))와 차이점?
  -- -> GROUP BY(MANAGER_ID, JOB_TITLE)한 것과 같다
  -- -> MANAGER_ID, JOB_TITLE 조합 별 집계

-- GROUPING SETS(JOB_TITLE, (MANAGER_ID, JOB_TITLE), ())와 차이점?
  -- -> 1) JOB_TITLE 로만 집계, 
  -- -> 2) MANAGER_ID와 JOB_TITLE의 조합별 집계
  -- -> 3) 전체 집계 ()
