-- 대기업 임직원 수 구하기
-- OUTTER JOIN과 INNER JOIN 중복된 데이터 출력되지 않도록 잘 조인하기

SELECT
    C.COMPANY_CODE, C.FOUNDER, 
    COUNT(DISTINCT L.LEAD_MANAGER_CODE),
    COUNT(DISTINCT S.SENIOR_MANAGER_CODE), 
    COUNT(DISTINCT M.MANAGER_CODE), 
    COUNT(DISTINCT E.EMPLOYEE_CODE)
FROM COMPANY C, LEAD_MANAGER L, SENIOR_MANAGER S, MANAGER M, EMPLOYEE E
WHERE C.COMPANY_CODE = L.COMPANY_CODE(+)
AND C.COMPANY_CODE = S.COMPANY_CODE(+)
AND S.LEAD_MANAGER_CODE = L.LEAD_MANAGER_CODE
AND C.COMPANY_CODE = M.COMPANY_CODE(+)
AND S.SENIOR_MANAGER_CODE = M.SENIOR_MANAGER_CODE
AND C.COMPANY_CODE = E.COMPANY_CODE(+)
AND M.MANAGER_CODE = E.MANAGER_CODE
GROUP BY C.COMPANY_CODE, C.FOUNDER
ORDER BY C.COMPANY_CODE;

-- 문제 출처: https://www.hackerrank.com/challenges/the-company/problem?isFullScreen=true
